title: Faith Sheppard | Computer SCience ePortfolio
logo: docs/assets/cover.JPG
description: CS 499 | ePortfolio | Southern New Hampshire University 2025
#show_downloads: true
theme: jekyll-theme-minimal
